name: rpmtw_dart_common_library
description: RPMTW common library for dart.
version: 1.0.0
homepage: https://www.rpmtw.com

environment:
  sdk: '>=2.15.0 <3.0.0'


dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies: {logger: ^1.1.0}
