name: Analyze
on:
  push:
    branches:
      - main
    paths:
      - "lib/**/*.dart"
      - "test/**/*.dart"
      - "pubspec.yaml"
  pull_request:

jobs:
  Analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache Dart
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/dart-sdk
          key: ${{ runner.os }}-dart-2.16.2
      # https://dart.dev/get-dart/archive
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: 2.16.2
      - name: Install dependencies
        run: |
          dart pub get
          dart pub global activate coverage
          export PATH="$PATH":"$HOME/.pub-cache/bin"

      - name: Dart Analyze
        uses: invertase/github-action-dart-analyzer@v1
        with:
          fatal-warnings: false
          annotate: true
          annotate-only: false
      - name: Generate Coverage
        run: |
          dart test --coverage="coverage"
          format_coverage --lcov --in=coverage --out=coverage.lcov --packages=.packages --report-on=lib
      - name: Update to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.lcov
